// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIZSvECYxjUbKXKDkcqoj8KRS-r1BdIKQ',
    appId: '1:139829389575:web:04d1b27f66c91d1fe83da2',
    messagingSenderId: '139829389575',
    projectId: 'qubiko-ai',
    authDomain: 'qubiko-ai.firebaseapp.com',
    storageBucket: 'qubiko-ai.firebasestorage.app',
    measurementId: 'G-Z4QSKL93Y0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdxmfHe-f806hUb2jy0FWHINVdIqdSaWE',
    appId: '1:139829389575:android:3bd2ea1a956d8d40e83da2',
    messagingSenderId: '139829389575',
    projectId: 'qubiko-ai',
    storageBucket: 'qubiko-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL1SSslekYaTVqL7RM73B1HHDCRmjxE50',
    appId: '1:139829389575:ios:dcb60e608dbfd0cee83da2',
    messagingSenderId: '139829389575',
    projectId: 'qubiko-ai',
    storageBucket: 'qubiko-ai.firebasestorage.app',
    iosBundleId: 'com.example.qubikoAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL1SSslekYaTVqL7RM73B1HHDCRmjxE50',
    appId: '1:139829389575:ios:dcb60e608dbfd0cee83da2',
    messagingSenderId: '139829389575',
    projectId: 'qubiko-ai',
    storageBucket: 'qubiko-ai.firebasestorage.app',
    iosBundleId: 'com.example.qubikoAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIZSvECYxjUbKXKDkcqoj8KRS-r1BdIKQ',
    appId: '1:139829389575:web:e3af440db10cd1c9e83da2',
    messagingSenderId: '139829389575',
    projectId: 'qubiko-ai',
    authDomain: 'qubiko-ai.firebaseapp.com',
    storageBucket: 'qubiko-ai.firebasestorage.app',
    measurementId: 'G-1YRG6M6CYE',
  );
}
